version : "3.8"

services:
  mysql:
    image: mysql:8.0.33
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thesisspringapp
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  spring-backend:
    build:
      context: '.'
    image: davidd071003/thesisspringapp
    environment:
      - HIBERNATE_CONNECTION_URL=jdbc:mysql://mysql:3306/thesisspringapp
      - HIBERNATE_CONNECTION_USERNAME=root
      - HIBERNATE_CONNECTION_PASSWORD=root
      - TZ=Asia/Ho_Chi_Minh
      - spring_fonts_fontvuArialFile=/usr/local/tomcat/webapps/thesisSpringApplication/resources/fonts/vuArial.ttf
      - spring_fonts_fontvuArialBoldFile=/usr/local/tomcat/webapps/thesisSpringApplication/resources/fonts/vuArialBold.ttf
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

  reactjs-frontend:
    image: thesis-web-app
    environment:
      REACT_APP_BASE_URL: http://localhost:8080/thesisSpringApplication/
    ports:
      - "3000:3000"
    depends_on:
      - spring-backend
      - mysql
    networks:
      - app-network

  
networks:
  app-network:

volumes:
  db_data: {}