version : "3.8"

services:
  mysql:
    image: mysql:8.1
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: thesisspringapp
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  application:
    build:
      context: '.'
    image: thesis-spring-app
    environment:
      HIBERNATE_CONNECTION_URL: jdbc:mysql://mysql:3306/thesisspringapp
      HIBERNATE_CONNECTION_USERNAME: root
      HIBERNATE_CONNECTION_PASSWORD: 12345
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

  web:
    image: thesis-web-app
    environment:
      REACT_APP_BASE_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - application
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data: {}